### PR TITLE
Sort and update imports in all scripts/modules

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR sorts and updates the imports blocks in all modules and scripts so that:

- imports are grouped in ordered based on the dependency chain
- imports in each group are alphabetically ordered
- imports using `six` have been updated to use the Python 3 module names
- unused imports have been removed

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
The packaging CI is failing because #88 isn't merged yet.

**Comment by duncanmmacleod** [comment]
@robertbruntz, this has been rebased on top of #87.

**Comment by robertbruntz** [comment]
@duncanmmacleod The changes to `dqsegdb/apicalls.py` break some functionality of 2 of the `dqsegdb` executables, since `from dqsegdb.urifunctions import *` is removed, and that is how `patchDataUrllib2` and `putDataUrllib2` were imported.  All other functions from `urifunctions.py` are called using the format `urifunctions.getDataUrllib2`, which is available from `from . import (clientutils, urifunctions,)`.  Unless there is some reason not to do so for the 2 unimported functions, I would suggest modifying the 4 instances of those functions (1 for `patchDataUrllib2` and 3 for `putDataUrllib2`) so that they are accessed as `urifunctions.patchDataUrllib2` and `urifunctions.putDataUrllib2`, which will be available due to the previously-mentioned import statement.

**Comment by duncanmmacleod** [comment]
@robertbruntz, I believe I have now corrected those issues, please confirm.

**Review by robertbruntz — APPROVED** [review]
All changes were visually inspected and investigated, then tested using the dqsegdb test suite (test_segments_machine.sh on the CIT cluster) in a dedicated venv; all tests passed.

**Pull request merged**
