### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR updates the project requirements based on suggestions from the LIGO packaging teams from the 3.0.1 release:

- require lscsoft-glue >=3.0.1
- add missing requirements on `six`
- use a versioned pyopenssl requirement everywhere
- remove old debian file

### CODE REVIEW

**Comment by steve8x8** [comment]
line 11 of `debian/control` is lacking a trailing comma... otherwise this looks fit for a -1.1 Debian build ;)

**Comment by robertbruntz** [comment]
@duncanmmacleod With the merger of https://github.com/ligovirgo/dqsegdb/pull/96 , I think `six` can be removed from requirements.

**Comment by duncanmmacleod** [comment]
> @duncanmmacleod With the merger of #96 , I think `six` can be removed from requirements.

rebased, thanks for the nudge.

**Comment by robertbruntz** [comment]
This PR is being closed because it has been moved to the new repo, here: https://git.ligo.org/computing/dqsegdb/client/-/merge_requests/109 , and was subsequently merged.

**Pull request closed without merging**
