### PR TITLE
Fix module shadowing by function argument

### LINKED ISSUE #17: Module variable being reassigned in urifunctions.py
The `warnings` module variable is being reassigned in `dqsegdb.urifunctions.getDataUrllib2`, resulting in an `AttributeError` when the `warnings.warn` method is called:

``` python
  File "/usr/lib/python2.7/site-packages/dqsegdb/apicalls.py", line 177, in dqsegdbQueryTimes
    result=urifunctions.getDataUrllib2(queryurl)
  File "/usr/lib/python2.7/site-packages/dqsegdb/urifunctions.py", line 114, in getDataUrllib2
    warnings.warn("Issue accesing url: %s; Reason: %s" % (url,str(e.reason)))
AttributeError: 'bool' object has no attribute 'warn'
```

This happens every time a `URLError` is raised from that method.

### PR DESCRIPTION
**Pull request by titodalcanton**
I renamed the import so as not to change the API.
Fixes #17 and #28.
Tested through `pycbc_coinc_time`.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@titodalcanton, thanks for this. However, does it not make a bit more sense to just

```python
from warnings import warn
```

then call `warn()` directly?

IMHO the correct solution is to actually rename the keyword argument `warnings` in the offending function, hopefully @rpfisher can comment on what that might break.

**Comment by titodalcanton** [comment]
There.

I'm worried of breaking third party scripts by changing the kwarg. Changing the import is harmless and shortens the code a bit too ;)

Travis seems unhappy on its own at the moment…

**Comment by duncanmmacleod** [comment]
@titodalcanton, travis-ci seem to have removed/changed the `allowed_failures` option, so the python3.5 build is now propagating to the top. python2.6 and python2.7 builds are passing, so we're fine.

**Comment by rpfisher** [comment]
Thanks very much for finding this bug.

**Pull request merged**
