### PR TITLE
Use pyOpenSSL instead of M2Crypto for X509 validation

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR modifies `dqsegdb.urifunctions` to use pyOpenSSL instead of M2Crypto when validating the X509 proxy.

This has been tested on python-2.7 via

```
ligolw_segment_query_dqsegdb --ping --segment-url https://segments.ligo.org
```

Included in this PR is a slight modification to `urifunctions.findCredential` to just raise a `RuntimeError` if the certificates cannot be found, rather than the custom `RFCproxyUsage()` message.

This adds a new dependency on pyOpenSSL, which is reflected in changes to `.travis.yml`, `setup.py`, and `requirements.txt`, but I'm not sure if this needs to be captured somewhere else as well for `.deb` or `.rpm` packaging.

### CODE REVIEW

**Comment by rpfisher** [comment]
Tested with basic queries, seems to work ok.  We should get people from VIRGO to test with their type of certs before accepting the PR.

**Comment by rpfisher** [comment]
Tested successfully with grid-proxy-init by Florent.  Also works with ligo-proxy-init of course.

**Comment by rpfisher** [comment]
Please update the PR to fix the conflicts in setup.py.

**Comment by duncanmmacleod** [comment]
@rpfisher, I have rebased this PR against master, and modified the commits to match. Once the CI completes you should be ok to merge.

**Pull request merged**
