### PR TITLE
First cut at travis configuration

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR adds a travis-ci.org configuration to install this package, and run a basic test of `$exe --help` for each script in `bin/`.

In order to make this work I had to make the following seemingly unrelated changes

- try/except import `pyRXPU` from pyRXP v2 rather than just `pyRXP`. this is the same change proposed in #4 - if this PR is merged, that one should be closed (rejected)
- deleted the README file in favour of the README.md

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@rpfisher, please wait before merging this, as I will probably want to test the travis configuration widely before declaring it done. I will assign to you when I'm ready, if thats ok.

**Comment by duncanmmacleod** [comment]
@rpfisher, for the record I think I'm done, please review the leading comment for a summary of the changes I have made. I made an effort to outline changes that might seem unrelated to the travis build setup.

**Comment by rpfisher** [comment]
Thanks again!

**Comment by spxiwh** [comment]
Would it be possible to make a new release including this commit please?

**Pull request merged**
